# .github/workflows/deploy.yml
name: Deploy Frontend to AWS EC2

# Event pemicu
on:
  push:
    branches:
      - main # Memicu workflow setiap kali ada push ke branch main

# Variabel lingkungan
env:
  DOCKER_HUB_USERNAME: luqmanul25
  FRONTEND_APP_NAME: uts-frontend-app

# Daftar pekerjaan (jobs)
jobs:
  # Job untuk membangun dan mendeploy aplikasi frontend
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ${DOCKER_HUB_USERNAME}/${FRONTEND_APP_NAME}:latest ./frontend-app
          docker push ${DOCKER_HUB_USERNAME}/${FRONTEND_APP_NAME}:latest

      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_FRONTEND_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          script: |
            # Set variables (fix untuk environment variables)
            DOCKER_HUB_USERNAME="luqmanul25"
            FRONTEND_APP_NAME="uts-frontend-app"

            # Menghentikan dan menghapus container lama secara paksa
            docker stop frontend-container || true
            docker rm -f frontend-container || true

            # Menarik image terbaru dari Docker Hub
            echo "Pulling image: ${DOCKER_HUB_USERNAME}/${FRONTEND_APP_NAME}:latest"
            docker pull ${DOCKER_HUB_USERNAME}/${FRONTEND_APP_NAME}:latest

            # Menjalankan container baru
            docker run -d -p 80:80 --name frontend-container \
              --restart unless-stopped \
              ${DOCKER_HUB_USERNAME}/${FRONTEND_APP_NAME}:latest

            # Cek status container
            docker ps
            docker logs frontend-container --tail 5
